[package]
name = "ssh-file"
version = "0.1.0"
authors = ["Ran Zvi <rantzvi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh2 = "0.9.1"
clap = "3.0.0-beta.2"
ctrlc = "3.1.9"
